
cmds = {
    'ls' : "To list file in the current directory\n",
    '--help' : "To show the tutorial on CLI\n",
    'pwd' : "To show the current working directory\n",
    'neofetch' : "To print the python ASCII\n",
    'date' : "To show the current date\n",
    'time' : "To show the current time\n",
    'ls': 'List directory contents\n',
    'cd': 'Change directory\n',
    'pwd': 'Print working directory\n',
    'mkdir': 'Make directories\n',
    'rmdir': 'Remove empty directories\n',
    'rm': 'Remove files or directories\n',
    'cp': 'Copy files or directories\n',
    'mv': 'Move or rename files or directories\n',
    'touch': 'Change file timestamps or create empty files\n',
    'cat': 'Concatenate and display file content\n',
    'more': 'View file content one screen at a time\n',
    'less': 'View file content with backward movement\n',
    'head': 'Display the beginning of a file\n',
    'tail': 'Display the end of a file\n',
    'grep': 'Search text using patterns\n',
    'find': 'Search for files in a directory hierarchy\n',
    'locate': 'Find files by name\n',
    'which': 'Locate a command\n',
    'man': 'Display the manual of a command\n',
    'chmod': 'Change file modes or Access Control Lists\n',
    'chown': 'Change file owner and group\n',
    'ps': 'Report process status\n',
    'top': 'Display Linux tasks\n',
    'kill': 'Send signals to processes\n',
    'killall': 'Kill processes by name\n',
    'df': 'Report file system disk space usage\n',
    'du': 'Estimate file space usage\n',
    'free': 'Display memory usage\n',
    'tar': 'Archive files\n',
    'gzip': 'Compress files\n',
    'gunzip': 'Decompress files\n',
    'zip': 'Package and compress files\n',
    'unzip': 'Extract compressed files\n',
    'ssh': 'OpenSSH remote login client\n',
    'scp': 'Securely copy files between hosts\n',
    'wget': 'Non-interactive network downloader\n',
    'curl': 'Transfer data from or to a server\n',
    'ping': 'Send ICMP ECHO_REQUEST to network hosts\n',
    'ifconfig': 'Configure a network interface (deprecated)\n',
    'ip': 'Show/manipulate routing, devices, policy routing, and tunnels\n',
    'netstat': 'Print network connections, routing tables, interface statistics\n',
    'route': 'Show/manipulate the IP routing table\n',
    'history': 'Show command history\n',
    'alias': 'Create an alias for a command\n',
    'unalias': 'Remove aliases\n',
    'sudo': 'Execute a command as another user\n',
    'passwd': 'Change user password\n',
    'useradd': 'Create a new user\n',
    'usermod': 'Modify a user account\n',
    'userdel': 'Delete a user account\n',
    'groupadd': 'Add a new group\n',
    'groupdel': 'Delete a group\n',
    'groups': 'Show user groups\n',
    'crontab': 'Schedule periodic tasks\n',
    'systemctl': 'Control the systemd system and service manager\n',
    'journalctl': 'Query and display messages from the journal\n',
    'service': 'Run a System V init script\n',
    'reboot': 'Reboot the system\n',
    'shutdown': 'Shutdown or restart the system\n'
}

